Repository decred/dcrdex, pull requests merged in 2020-10, with the labels that each got.

#442 client/core: handle trade resumption messages.
  client/core/core.go
  client/core/core_test.go
  client/core/types.go
Labels: client, high priority

#705 suspend/resume
  client/cmd/dexc/ui/config.go
  client/core/bookie.go
  client/core/core.go
  client/core/core_test.go
  client/core/errors.go
  client/core/trade.go
  client/core/types.go
  client/order/orderbook.go
  client/order/orderbook_test.go
  client/webserver/site/src/js/markets.js
  dex/msgjson/types.go
  dex/runner.go
  server/admin/api.go
  server/admin/server.go
  server/admin/server_test.go
  server/admin/types.go
  server/dex/dex.go
  server/market/bookrouter.go
  server/market/market.go
  server/market/orderrouter.go
Labels: high priority

#700 auth,db,++: ban score accounting, cancel order limits and controls
  client/core/core.go
  dex/market.go
  dex/msgjson/types.go
  dex/order/match.go
  dex/order/status.go
  server/admin/api.go
  server/admin/server.go
  server/admin/server_test.go
  server/admin/types.go
  server/auth/auth.go
  server/auth/auth_test.go
  server/auth/cancel.go
  server/auth/latest.go
  server/auth/latest_test.go
  server/cmd/dcrdex/config.go
  server/cmd/dcrdex/main.go
  server/db/driver/pg/accounts_online_test.go
  server/db/driver/pg/internal/accounts.go
  server/db/driver/pg/internal/matches.go
  server/db/driver/pg/internal/orders.go
  server/db/driver/pg/markets.go
  server/db/driver/pg/matches.go
  server/db/driver/pg/orders.go
  server/db/driver/pg/system.go
  server/db/driver/pg/tables.go
  server/db/interface.go
  server/dex/dex.go
  server/market/epoch.go
  server/market/market.go
  server/market/market_test.go
  server/market/orderrouter.go
  server/market/routers_test.go
  server/swap/swap.go
  server/swap/swap_test.go
Labels: high priority

#748 client/core: fix resendPendingRequest sending wrong redeem coin
  client/core/core.go
  client/core/status.go
  client/core/trade.go
  client/core/trade_simnet_test.go
Labels: bug, high priority

#741 assets: implement segwit btc swap contracts
  client/asset/btc/btc.go
  client/asset/btc/btc_test.go
  client/asset/btc/livetest/livetest.go
  client/asset/btc/livetest/regnet_test.go
  client/asset/btc/walletclient.go
  client/asset/dcr/dcr.go
  client/asset/dcr/dcr_test.go
  client/asset/ltc/ltc.go
  dex/networks/btc/script.go
  dex/networks/btc/script_test.go
  server/asset/btc/btc.go
  server/asset/btc/btc_test.go
  server/asset/btc/testing.go
  server/asset/btc/utxo.go
  server/asset/ltc/ltc.go
  server/market/orderrouter.go
Labels: high priority

#732 market: verify unspent status of unfilled orders
  server/book/book.go
  server/book/orderpq.go
  server/market/market.go
  server/market/orderrouter.go
  server/market/routers_test.go
Labels: high priority

#745 client/core: split locked balances in categories
  client/asset/interface.go
  client/core/core.go
  client/core/trade.go
  client/core/types.go
Labels: high priority

#754 websocket read limits, raised on auth
  client/websocket/websocket.go
  client/websocket/websocket_test.go
  dex/ws/wslink.go
  dex/ws/wslink_test.go
  server/auth/auth.go
  server/auth/auth_test.go
  server/comms/comms_test.go
  server/comms/link.go
  server/market/routers_test.go
Labels: bug, high priority

#750 server/{auth,db,market,swap}: user order quantity limits
  client/asset/dcr/dcr.go
  client/core/core.go
  dex/calc/convert.go
  dex/msgjson/types.go
  server/auth/auth.go
  server/auth/auth_test.go
  server/auth/latest.go
  server/auth/latest_test.go
  server/book/book.go
  server/db/driver/pg/internal/matches.go
  server/db/driver/pg/internal/orders.go
  server/db/driver/pg/matches.go
  server/db/driver/pg/orders.go
  server/db/interface.go
  server/market/market.go
  server/market/market_test.go
  server/market/orderrouter.go
  server/market/routers_test.go
  server/matcher/match_test.go
  server/swap/swap.go
  server/swap/swap_test.go
Labels: high priority

#738 client: add Tor support
  .github/workflows/build.yml
  client/cmd/dexc/main.go
  client/cmd/dexc/ui/config.go
  client/comms/wsconn.go
  client/core/core.go
  client/core/core_test.go
  dex/networks/btc/script.go
  go.mod
Labels: high priority
