Repository decred/dcrdex, pull requests merged in 2021-09, with the labels that each got.

#1197 client/{core,db}: add topic IDs to notifications
  client/core/bookie.go
  client/core/core.go
  client/core/core_test.go
  client/core/locale_en.go
  client/core/notification.go
  client/core/trade.go
  client/core/trade_simnet_test.go
  client/db/types.go
  client/webserver/live_test.go
  client/webserver/site/src/js/app.js
  client/webserver/site/src/js/markets.js
  dex/testing/loadbot/mantle.go
  dex/testing/loadbot/pingpong.go
Labels: i18n

#1127 js intl
  client/cmd/dexc/main.go
  client/core/core.go
  client/core/locale_ntfn.go
  client/webserver/locales/en-us.go
  client/webserver/site/package.json
  client/webserver/site/src/html/bodybuilder.tmpl
  client/webserver/site/src/html/wallets.tmpl
  client/webserver/site/src/js/app.js
  client/webserver/site/src/js/doc.js
  client/webserver/site/src/js/forms.js
  client/webserver/site/src/js/locales.js
  client/webserver/site/src/js/login.js
  client/webserver/site/src/js/markets.js
  client/webserver/site/src/js/order.js
  client/webserver/site/src/js/register.js
  client/webserver/site/src/js/settings.js
  client/webserver/site/src/js/wallets.js
  client/webserver/site/src/localized_html/en-US/bodybuilder.tmpl
  client/webserver/webserver.go
Labels: i18n

#1189 webserver: retranslate template when --reload-html is used
  client/webserver/locales/parse.go
  client/webserver/site/template-builder/main.go
  client/webserver/template.go
  client/webserver/webserver.go
Labels: i18n

#1205 eth/testing: Ensure node shutdown happens.
  client/asset/eth/rpcclient_harness_test.go
  server/asset/eth/rpcclient_harness_test.go
Labels: ETH

#1185 i18n: add pt-BR translations
  client/core/locale_ntfn.go
  client/webserver/locales/locales.go
  client/webserver/locales/pt-br.go
  client/webserver/site/src/js/locales.js
  client/webserver/site/src/js/markets.js
  client/webserver/site/src/localized_html/pt-BR/bodybuilder.tmpl
  client/webserver/site/src/localized_html/pt-BR/forms.tmpl
  client/webserver/site/src/localized_html/pt-BR/login.tmpl
  client/webserver/site/src/localized_html/pt-BR/markets.tmpl
  client/webserver/site/src/localized_html/pt-BR/order.tmpl
  client/webserver/site/src/localized_html/pt-BR/orders.tmpl
  client/webserver/site/src/localized_html/pt-BR/register.tmpl
  client/webserver/site/src/localized_html/pt-BR/settings.tmpl
  client/webserver/site/src/localized_html/pt-BR/wallets.tmpl
Labels: i18n

#1177 [0.3] dexc: comment eth import for release
  client/cmd/dexc/main.go
Labels: ETH

#1215 networks/eth: Add methods to decode tx data.
  client/asset/eth/config.go
  client/asset/eth/doc.go
  client/asset/eth/eth.go
  client/asset/eth/eth_test.go
  client/asset/eth/node.go
  client/asset/eth/rpcclient.go
  client/asset/eth/rpcclient_harness_test.go
  client/cmd/dexc/importlgpl.go
  client/cmd/dexc/main.go
  dex/networks/eth/abi.go
  dex/networks/eth/abi_test.go
  dex/networks/eth/doc.go
  dex/networks/eth/txdata.go
  dex/networks/eth/txdata_test.go
  dex/testing/dcrdex/harness.sh
  run_tests.sh
  server/asset/eth/cache.go
  server/asset/eth/common.go
  server/asset/eth/config.go
  server/asset/eth/doc.go
  server/asset/eth/eth.go
  server/asset/eth/eth_test.go
  server/asset/eth/rpcclient.go
  server/asset/eth/rpcclient_harness_test.go
  server/cmd/dcrdex/importlgpl.go
  server/cmd/dcrdex/main.go
Labels: ETH

#1089 client: prepare interfaces for bitcoin spv
  client/asset/bch/bch.go
  client/asset/btc/btc.go
  client/asset/btc/btc_test.go
  client/asset/btc/livetest/livetest.go
  client/asset/btc/rpcclient.go
  client/asset/btc/wallet.go
  client/asset/btc/wallettypes.go
  client/asset/dcr/dcr.go
  client/asset/dcr/dcr_test.go
  client/asset/dcr/simnet_test.go
  client/asset/eth/eth.go
  client/asset/interface.go
  client/core/core.go
  client/core/core_test.go
  client/core/trade.go
  client/core/wallet.go
  dex/networks/btc/script.go
  dex/networks/btc/script_test.go
  dex/testing/loadbot/go.sum
Labels: SPV

#1184 eth/client: Implement MaxOrder
  client/asset/eth/eth.go
  client/asset/eth/eth_test.go
  client/asset/eth/rpcclient.go
  client/asset/eth/rpcclient_harness_test.go
Labels: ETH
