Repository decred/dcrdex, pull requests merged in 2022-10, with the labels that each got.

#1845 client: No hide header when having additional settings
  client/webserver/site/src/js/forms.ts
Labels: UI

#1871 client: updates for zh-CN
  client/core/locale_ntfn.go
  client/webserver/locales/zh-cn.go
  client/webserver/site/src/js/locales.ts
Labels: i18n

#1894 core/eth: Handle block gas limit
  client/asset/eth/eth.go
  client/asset/eth/eth_test.go
  client/asset/interface.go
  client/core/core_test.go
  client/core/trade.go
Labels: ETH

#1847 client: hide accelerate button after first maker's swap
  client/webserver/site/src/js/markets.ts
Labels: UI

#1899 docs: add release notes for v0.5.3 and v0.5.4
  docs/release-notes/release-notes-0.5.3.md
  docs/release-notes/release-notes-0.5.4.md
Labels: documentation
