Repository decred/dcrdex, pull requests merged in 2023-03, with the labels that each got.

#2233 wiki: add Ethereum page
  docs/wiki/Ethereum.md
  docs/wiki/images/eth-create-wallet.png
  docs/wiki/images/eth-wallet-settings.png
Labels: documentation

#2247 client/eth: balance change trigger pending txs recheck
  client/asset/eth/eth.go
  client/asset/eth/eth_test.go
Labels: ETH

#2248 server/asset: trade address validation consistency
  server/asset/btc/btc.go
  server/asset/btc/btc_test.go
  server/asset/common.go
  server/asset/dcr/dcr.go
  server/asset/dcr/dcr_test.go
  server/asset/eth/eth.go
  server/market/orderrouter.go
  server/market/routers_test.go
  server/swap/swap_test.go
Labels: bug
