Repository decred/dcrdex, pull requests merged in 2023-01, with the labels that each got.

#2008 client/asset/{btc,dcr}: maintain sync progress after losing peers
  client/asset/btc/spv_wrapper.go
  client/asset/dcr/spv.go
Labels: bug

#2011 client/asset/dcr: refund method recognizes spends in refunds
  client/asset/dcr/dcr.go
  client/asset/dcr/externaltx.go
  dex/networks/dcr/script.go
  dex/networks/dcr/script_test.go
Labels: bug, wallet

#2001 spec: Update fundamentals.
  dex/msgjson/types.go
  spec/fundamentals.mediawiki
  spec/references.mediawiki
Labels: spec

#2030 Optimized Docker base images
  client/Dockerfile
Labels: docker

#2035 [docker] Run dexc as non-root user
  client/Dockerfile
Labels: docker

#2021 server/swap: avoid deadlock with maker redeem ack
  server/swap/swap.go
Labels: bug

#2034 eth: Always check header time.
  client/asset/eth/eth.go
  server/asset/eth/eth.go
  server/asset/eth/eth_test.go
Labels: bug

#1978 ui: display Maker redeem found by Taker
  client/asset/eth/eth.go
  client/asset/eth/fundingcoin.go
  client/core/types.go
  client/webserver/site/src/js/locales.ts
  client/webserver/site/src/js/order.ts
Labels: bug, frontend

#2047 server/eth: Allow geth connections using http and ws
  client/asset/eth/multirpc.go
  dex/networks/erc20/contracts/TestToken.sol
  dex/networks/eth/common.go
  dex/testing/dcrdex/harness.sh
  dex/testing/eth/create-node.sh
  dex/testing/eth/harness.sh
  server/asset/eth/eth.go
  server/asset/eth/rpcclient.go
  server/asset/eth/rpcclient_harness_test.go
Labels: ETH

#2002 ui: uniform responsive checkbox
  client/webserver/site/src/css/main.scss
  client/webserver/site/src/css/main_dark.scss
  client/webserver/site/src/html/forms.tmpl
  client/webserver/site/src/html/register.tmpl
  client/webserver/site/src/html/wallets.tmpl
Labels: frontend

#2059 server/eth: Do not use txpool when calculating balance if not supported
  server/asset/eth/rpcclient.go
Labels: ETH

#1975 ui: store markets/wallets user preferences
  client/webserver/locales/parse_test.go
  client/webserver/middleware.go
  client/webserver/site/src/css/market.scss
  client/webserver/site/src/css/market_dark.scss
  client/webserver/site/src/html/bodybuilder.tmpl
  client/webserver/site/src/html/markets.tmpl
  client/webserver/site/src/html/settings.tmpl
  client/webserver/site/src/js/app.ts
  client/webserver/site/src/js/markets.ts
  client/webserver/site/src/js/mm.ts
  client/webserver/site/src/js/settings.ts
  client/webserver/site/src/js/state.ts
  client/webserver/site/src/js/wallets.ts
  client/webserver/webserver.go
Labels: frontend
